### ISSUE TITLE
Understanding mutations pattern

### ISSUE THREAD

**Issue by mlwilkerson** [SenteraLLC/graphql-subscriptions-spike#3]
I'm trying to understand the mutations pattern used in the React client here:

It looks like when you [fire `mutate()`](https://github.com/SenteraLLC/graphql-subscriptions-spike/blob/a3c08b70369f1dbb0d82b2513c002865898b7171/graphql-subscriptions-react/src/components/PostEditorView.js#L30-L30) in `PostEditorView`, for example, the mutation gets back a `process_id`. But that `process_id` is never used for anything. Rather, the real result of that mutation—the newly created post—comes back to the client via ActionCable broadcast separately, right? Without regard to that `process_id`?

I think I have a sense for why this is the pattern (it keeps data flow unidirectional, for one). But I also notice that both mutations in this example (for posts and comments), operate on objects for which you have a subscription. So I wonder, would you still be using this same pattern for objects for which you _don't_ have a subscription? Or would you end up subscribing to every object on the page, or something else?

Imagine you were going to add Tags to the Posts. Then you have a mutation that adds a tag, would you be using the same pattern?

**Comment by cebartling** [comment]
@mlwilkerson This example is somewhat contrived so we could demonstrate GraphQL subscriptions and we chose to use the mutations as a trigger for the subscriptions. I wouldn't take our implementation as an example of how mutations should be patterned. We needed to show how the the ActionCable plumbing worked with `ruby-graphql`, and the mutation provided a simple trigger for that.

**Comment by mlwilkerson** [comment]
OK, thanks.
